name = "gtransducer"
version = "1.0.0"
description = ""
licences = ["MIT"]
repository = { type = "github", user = "nohzafk", repo = "gtransducer" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
